language: java
sudo: enabled
jdk:
- oraclejdk8

script:
    - mvn install
    
before_install:
    - chmod +x mvnw

# services:
#     - postgresql

# before_script:
#     - psql -c 'create database vv'
