language: java
sudo: enabled
jdk:
- oraclejdk8

addons:
  sonarcloud:
    organization: davicedraz-github # the key of the org you chose at step #3
    token:
      secure: acbe4e9f247a37a80d21ea6b4b94046f50d64636 # encrypted value of your token

script:
    - mvn install
   - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
    
before_install:
    - chmod +x mvnw

services:
    - postgresql

before_script:
    - psql -c 'create database vv;' -U postgres
#- psql -c 'create user postgres with password '1234';' -U postgres
